PUT http://localhost:8080/api/produtos/atualizar/10
Content-Type: application/json

{
  "nome": "Fraldinha",
  "descricao": "Carne adequada para churrasco",
  "preco": 40,
  "quantidadeEstoque": 100
}

